### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [Jblew/marinesmud-3d#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by Jblew** [comment]
MIT :)

**Comment by suprafun** [comment]
Thank-you sooo very much for your generosity : D . One further question, I just saw that you have a server component as well ( AlternativMUD server, I believe found here : https://github.com/Jblew/alternativ-mud ), under what license is that server project released under ? I would like to really study them both very closely so I can come up with my own project : D Thank-you again.

**Comment by Jblew** [comment]
Its nice, you like it :) Its quite old and unfinished project, but I hope you'll find it helpful. Alternativ-mud and marinesmud-framework are under MIT as well. If you have any questions or encounter any problems running the project you can text me at: jedrzejblew@gmail.com
